name: main build

on:
 push: 
 # tags:
 #  - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Install dependencies
        working-directory: ./ActionsApp
        run: dotnet restore
      - name: Build
        working-directory: ./ActionsApp
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./ActionsApp
        run: dotnet test --no-restore --verbosity normal     
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md
      - name: Create Relase
        uses: ncipollo/release-action@v1
        with:
          tag: "1.1"
          body: New Release
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./ActionsApp/bin/Release/netcoreapp3.1/ActionsApp" 

      


