name: main build

on:
 push: 
  branches:
   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Install dependencies
        working-directory: ./ActionsApp
        run: dotnet restore
      - name: Build
        working-directory: ./ActionsApp
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./ActionsApp
        run: dotnet test --no-restore --verbosity normal     
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md

      


